version: '2'
services:
  nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/certs:/etc/nginx/certs
      ports:
      - 80:80
      - 443:443
      - 5044:5044

  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
      - ${PWD}/certbot-etc:/etc/letsencrypt
      - ${PWD}/certbot-var:/var/lib/letsencrypt
      - ${PWD}/web-root:/var/www/html
      depends_on:
      - nginx
      #command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com 
networks:
  default:
    external:
      name: container-net